export const fieldTypes = [
    "title",
    "year",
    "length (min)",
    "result size",
    "genre",
    "IMDb rating",
    "acclaim",
    "director(s)",
    "language",
    "actor(s)",
    "writer(s)",
]

export const genres = [
    "action",
    "adventure",
    "animation",
    "biography",
    "comedy",
    "crime",
    "documentary",
    "drama",
    "family",
    "fantasy",
    "film-noir",
    "history",
    "horror",
    "music",
    "musical",
    "mystery",
    "romance",
    "sci-fi",
    "sport",
    "thriller",
    "war",
    "western"
]

export const languages = [
    "abkhazian",
    "afrikaans",
    "amharic",
    "arabic",
    "aymara",
    "bulgarian",
    "bambara",
    "bengali",
    "tibetan",
    "bosnian",
    "catalan",
    "chinese",
    "czech",
    "welsh",
    "danish",
    "german",
    "greek",
    "english",
    "esperanto",
    "spanish",
    "estonian",
    "basque",
    "persian (farsi)",
    "finnish",
    "french",
    "frisian",
    "galician",
    "hebrew (modern)",
    "hindi",
    "croatian",
    "hungarian",
    "armenian",
    "indonesian",
    "icelandic",
    "italian",
    "inuktitut",
    "japanese",
    "javanese",
    "georgian",
    "kazakh",
    "kannada",
    "korean",
    "kurdish",
    "kyrgyz",
    "latin",
    "luxembourgish",
    "lao",
    "lithuanian",
    "latvian",
    "macedonian",
    "malayalam",
    "mongolian",
    "marathi",
    "malay",
    "maltese",
    "norwegian bokmål",
    "nepali",
    "dutch",
    "norwegian",
    "punjabi",
    "polish",
    "pashto",
    "portuguese",
    "quechua",
    "romanian",
    "russian",
    "kinyarwanda",
    "serbo-croatian",
    "sinhala",
    "slovak",
    "slovenian",
    "samoan",
    "albanian",
    "serbian",
    "swedish",
    "tamil",
    "telugu",
    "tajik",
    "thai",
    "tagalog",
    "turkish",
    "ukrainian",
    "urdu",
    "uzbek",
    "vietnamese",
    "wolof",
    "chinese (mandarin)",
    "zulu"
]


export const dropdowns: {fieldtype: string, multisAllowed: number}[] = [
    {fieldtype: "result size", multisAllowed: 1},
    {fieldtype: "genre", multisAllowed: 3},
    {fieldtype: "language", multisAllowed: 1}
]


export const doubleDropdowns = [
	"year",
	"length (min)",
	"IMDb rating",
	"acclaim",
]


export const languageMap = [
    ["ab", "abkhazian"],
    ["af", "afrikaans"],
    ["am", "amharic"],
    ["ar", "arabic"],
    ["ay", "aymara"],
    ["bg", "bulgarian"],
    ["bm", "bambara"],
    ["bn", "bengali"],
    ["bo", "tibetan"],
    ["bs", "bosnian"],
    ["ca", "catalan"],
    ["cn", "chinese"],
    ["cs", "czech"],
    ["cy", "welsh"],
    ["da", "danish"],
    ["de", "german"],
    ["el", "greek"],
    ["en", "english"],
    ["eo", "esperanto"],
    ["es", "spanish"],
    ["et", "estonian"],
    ["eu", "basque"],
    ["fa", "persian (farsi)"],
    ["fi", "finnish"],
    ["fr", "french"],
    ["fy", "frisian"],
    ["gl", "galician"],
    ["he", "hebrew (modern)"],
    ["hi", "hindi"],
    ["hr", "croatian"],
    ["hu", "hungarian"],
    ["hy", "armenian"],
    ["id", "indonesian"],
    ["is", "icelandic"],
    ["it", "italian"],
    ["iu", "inuktitut"],
    ["ja", "japanese"],
    ["jv", "javanese"],
    ["ka", "georgian"],
    ["kk", "kazakh"],
    ["kn", "kannada"],
    ["ko", "korean"],
    ["ku", "kurdish"],
    ["ky", "kyrgyz"],
    ["la", "latin"],
    ["lb", "luxembourgish"],
    ["lo", "lao"],
    ["lt", "lithuanian"],
    ["lv", "latvian"],
    ["mk", "macedonian"],
    ["ml", "malayalam"],
    ["mn", "mongolian"],
    ["mr", "marathi"],
    ["ms", "malay"],
    ["mt", "maltese"],
    ["nb", "norwegian bokmål"],
    ["ne", "nepali"],
    ["nl", "dutch"],
    ["no", "norwegian"],
    ["pa", "punjabi"],
    ["pl", "polish"],
    ["ps", "pashto"],
    ["pt", "portuguese"],
    ["qu", "quechua"],
    ["ro", "romanian"],
    ["ru", "russian"],
    ["rw", "kinyarwanda"],
    ["sh", "serbo-croatian"],
    ["si", "sinhala"],
    ["sk", "slovak"],
    ["sl", "slovenian"],
    ["sm", "samoan"],
    ["sq", "albanian"],
    ["sr", "serbian"],
    ["sv", "swedish"],
    ["ta", "tamil"],
    ["te", "telugu"],
    ["tg", "tajik"],
    ["th", "thai"],
    ["tl", "tagalog"],
    ["tr", "turkish"],
    ["uk", "ukrainian"],
    ["ur", "urdu"],
    ["uz", "uzbek"],
    ["vi", "vietnamese"],
    ["wo", "wolof"],
    ["xx", "no language specified"],
    ["zh", "chinese (mandarin)"],
    ["zu", "zulu"],
]
